// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTJKyjj9OjgTO-bNssZ4d3yf0zAvZpSBA',
    appId: '1:166195661856:web:ea8a1a48a620eecd730045',
    messagingSenderId: '166195661856',
    projectId: 'ministerio-publico-cbt',
    authDomain: 'ministerio-publico-cbt.firebaseapp.com',
    storageBucket: 'ministerio-publico-cbt.firebasestorage.app',
    measurementId: 'G-Z8PV14EVPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd8EiZW19_KB4uKaWqVgObPc6mJj6kKis',
    appId: '1:166195661856:android:5e22920ffaf36f32730045',
    messagingSenderId: '166195661856',
    projectId: 'ministerio-publico-cbt',
    storageBucket: 'ministerio-publico-cbt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq6g6xT3XvNCrqoIEBKQZuwoZgR8t9sB0',
    appId: '1:166195661856:ios:6e0765f603ae6cac730045',
    messagingSenderId: '166195661856',
    projectId: 'ministerio-publico-cbt',
    storageBucket: 'ministerio-publico-cbt.firebasestorage.app',
    iosBundleId: 'com.example.ministerioPublicoCbt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq6g6xT3XvNCrqoIEBKQZuwoZgR8t9sB0',
    appId: '1:166195661856:ios:6e0765f603ae6cac730045',
    messagingSenderId: '166195661856',
    projectId: 'ministerio-publico-cbt',
    storageBucket: 'ministerio-publico-cbt.firebasestorage.app',
    iosBundleId: 'com.example.ministerioPublicoCbt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTJKyjj9OjgTO-bNssZ4d3yf0zAvZpSBA',
    appId: '1:166195661856:web:6d2aaa9c681f4904730045',
    messagingSenderId: '166195661856',
    projectId: 'ministerio-publico-cbt',
    authDomain: 'ministerio-publico-cbt.firebaseapp.com',
    storageBucket: 'ministerio-publico-cbt.firebasestorage.app',
    measurementId: 'G-61P3ZTMEL0',
  );
}
